CREATE TABLE IF NOT EXISTS board (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS card (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id    BIGINT        NOT NULL,
    type        VARCHAR(20)   NOT NULL,
    title       VARCHAR(200)  NOT NULL,
    description VARCHAR(1000),
    priority    VARCHAR(10)   NOT NULL,
    status      VARCHAR(20)   NOT NULL,
    created_at  TIMESTAMP     NOT NULL,
    CONSTRAINT fk_card_board FOREIGN KEY (board_id) REFERENCES board (id)
);
